added implementation of NSGA-II and fixed some bugs.
Also discovered that Op2GeneralizedAlternatingPosition has a bug, but do not know where yet.

Can be reproduced as follows:

```
from typing import List

from moptipy.algorithms.mo.nsga2 import NSGA2
from moptipy.api.mo_archive import MORecord
from moptipy.api.mo_execution import MOExecution
from moptipy.examples.jssp.gantt_space import GanttSpace
from moptipy.examples.jssp.instance import Instance
from moptipy.examples.jssp.makespan import Makespan
from moptipy.examples.jssp.ob_encoding import OperationBasedEncoding
from moptipy.examples.jssp.worktime import Worktime
from moptipy.mo.problem.weighted_sum import Prioritize
from moptipy.operators.permutations.op0_shuffle import Op0Shuffle
from moptipy.operators.permutations.op1_swapn import Op1SwapN
from moptipy.spaces.permutations import Permutations
from moptipy.operators.permutations.op2_gap import Op2GeneralizedAlternatingPosition
from moptipy.utils.nputils import array_to_str
from moptipy.utils.temp import TempFile

instance = Instance.from_resource("swv02")     # We load the instance "swv02".
solution_space = GanttSpace(instance)          # Solutions are Gantt charts.
search_space = Permutations.with_repetitions(  # We will encode solutions as
    instance.jobs, instance.machines)          # permutations w. repetitions.
encoding = OperationBasedEncoding(instance)    # Decode permutations to Gantt.

# Each multi-objective optimization problem is defined by several objective
# functions *and* a way to scalarize the vector of objective values.
# The scalarization is only used by the system to decide for one single best
# solution in the end *and* if we actually apply a single-objective algorithm
# to the problem instead of a multi-objective one. (Here we will apply a
# multi-objective algorithm.)
f1 = Makespan(instance)  # The first objective be the makespan.
f2 = Worktime(instance)  # The second objective be the total work time.
# Here, we decide for a priorization scalarization: The single best end result
# will be the one with the shortest makespan.
problem = Prioritize([f1, f2])

algorithm = NSGA2(              # Create multi-objective RLS that
    Op0Shuffle(search_space),   # starts with a random permutation and
    Op1SwapN(),                 # swaps a random number of elements per step.
    Op2GeneralizedAlternatingPosition(search_space),
    16, 0.05)

# We execute the whole experiment in a temp directory.
# For a real experiment, you would put an existing directory path in `td`
# by doing `from moptipy.utils.path import Path; td = Path.directory("mydir")`
# and not use the `with` block.
with TempFile.create() as tf:  # create temporary file `tf`
    ex = MOExecution()  # begin configuring execution
    ex.set_solution_space(solution_space)
    ex.set_search_space(search_space)
    ex.set_encoding(encoding)
    ex.set_objective(problem)      # set the multi-objective problem
    ex.set_algorithm(algorithm)
    ex.set_rand_seed(199)          # set random seed to 199
    ex.set_log_improvements(True)  # log all improving moves
    ex.set_log_file(tf)            # set log file = temp file `tf`
    ex.set_max_fes(2800)           # allow at most 2800 function evaluations
    with ex.execute() as process:  # now run the algorithm*problem combination
        arch: List[MORecord] = process.get_archive()
        print(f"We found the {len(arch)} non-dominated trade-off solutions:")
        print("makespan;worktime")
        arch.sort()
        for ae in arch:
            print(array_to_str(ae.fs))

    print("\nNow reading and printing all the logged data:")
    print(tf.read_all_str())  # instead, we load and print the log file
# The temp file is deleted as soon as we leave the `with` block.
```

which gives:

```
/usr/bin/python3.10 examples/mo_example2.py
We found the 2 non-dominated trade-off solutions:
makespan;worktime
2225;11935
2244;11839
Traceback (most recent call last):
  File "examples/mo_example2.py", line 85, in <module>
    with ex.execute() as process:  # now run the algorithm*problem combination
  File "moptipy/api/_process_base.py", line 562, in __exit__
    raise self._caught  # pylint: disable=[E0702]
  File "moptipy/api/mo_execution.py", line 340, in execute
    algorithm.solve(process)
  File "moptipy/api/mo_algorithm.py", line 22, in solve
    self.solve_mo(cast(MOProcess, process))
  File "moptipy/algorithms/mo/nsga2.py", line 266, in solve_mo
    evaluate(ofs.x, ofs.fs)  # otherwise: evaluate
  File "moptipy/api/_mo_process_ss_log.py", line 89, in f_evaluate
    self._search_space.validate(x)
  File "moptipy/spaces/permutations.py", line 214, in validate
    raise ValueError(
ValueError: expected to find 5 exactly 10 times but found it 11 times.

Process finished with exit code 1
```